[package]
name = "declarative-scoop"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
miette = { version = "7.5.0", features = ["fancy"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
